# Generated by Django 5.1.4 on 2025-01-10 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksdone',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выполнения работ'),
        ),
    ]
