# Generated by Django 5.1.4 on 2024-12-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Работник'),
        ),
    ]
