# Generated by Django 5.1.4 on 2025-01-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0002_alter_worker_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='total_salary_paid',
        ),
        migrations.AddField(
            model_name='worker',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='зарплата'),
        ),
    ]
