# Generated by Django 5.1.4 on 2025-01-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0002_alter_worksdone_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Operations',
            new_name='Operation',
        ),
        migrations.RenameModel(
            old_name='WorksDone',
            new_name='OperationLog',
        ),
    ]
