# Generated by Django 5.1.4 on 2025-01-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0003_rename_operations_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='id_telegram',
            field=models.IntegerField(null=True, unique=True, verbose_name='ID телеграм'),
        ),
    ]
