# Generated by Django 5.1.4 on 2025-01-12 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0004_worker_id_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='admins_rights',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='work_place',
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Должность')),
                ('admins_rights', models.BooleanField(default=False, verbose_name='Права админа')),
                ('default_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins_panel.operation')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.AddField(
            model_name='worker',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admins_panel.position'),
        ),
    ]
