# Generated by Django 5.1.4 on 2025-01-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0005_remove_worker_admins_rights_remove_worker_work_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(verbose_name='Цена товара'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='price',
            field=models.FloatField(verbose_name='Цена операции'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=models.FloatField(default=0, verbose_name='зарплата'),
        ),
    ]
