# Generated by Django 5.1.4 on 2025-01-20 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0008_worker_have_telegram_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='id_telegram',
            new_name='telegram_id',
        ),
    ]
