# Generated by Django 5.1.4 on 2025-01-21 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0009_rename_id_telegram_worker_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'permissions': [('can_add_product', 'Can add product'), ('can_remove_product', 'Can remove product'), ('can_give_salary', 'Can give salary')], 'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
    ]
