# Generated by Django 5.1.4 on 2025-01-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0010_alter_worker_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
    ]
