# Generated by Django 5.1.4 on 2025-01-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0011_alter_worker_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='udit_goods',
            field=models.BooleanField(default=False, verbose_name='Права на редактирование товаров'),
        ),
    ]
