# Generated by Django 5.1.4 on 2025-01-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0012_position_udit_goods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='udit_goods',
            new_name='edit_goods',
        ),
    ]
