# Generated by Django 5.1.4 on 2025-01-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0013_rename_udit_goods_position_edit_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет товара'),
        ),
        migrations.AddField(
            model_name='goods',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер товара'),
        ),
    ]
