# Generated by Django 5.1.4 on 2025-01-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0014_goods_color_goods_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='edit_goods_custom_vession',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Права на редактирование товаров, расширенная версия'),
        ),
    ]
