# Generated by Django 5.1.4 on 2025-01-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0015_position_edit_goods_custom_vession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='edit_goods_custom_vession',
            new_name='edit_goods_custom_version',
        ),
    ]
