# Generated by Django 5.1.4 on 2025-01-22 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0016_rename_edit_goods_custom_vession_position_edit_goods_custom_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата выпуска товара'),
        ),
    ]
