# Generated by Django 5.1.4 on 2025-01-23 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0017_goods_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='edit_goods_custom_version',
        ),
    ]
