# Generated by Django 5.1.4 on 2025-01-25 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0018_remove_position_edit_goods_custom_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='color',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='size',
        ),
    ]
