# Generated by Django 5.1.4 on 2025-01-25 04:41

import admins_panel.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0019_remove_goods_color_remove_goods_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='release_date',
        ),
        migrations.CreateModel(
            name='GoodsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество товара')),
                ('release_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата выпуска товара')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admins_panel.goods')),
                ('worker', models.ForeignKey(default=admins_panel.models.Worker.get_deleted_worker, on_delete=django.db.models.deletion.SET_DEFAULT, to='admins_panel.worker')),
            ],
            options={
                'verbose_name': 'Выпущенный товар',
                'verbose_name_plural': 'Выпущенные товары',
            },
        ),
    ]
