# Generated by Django 5.1.4 on 2025-01-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0020_remove_goods_quantity_remove_goods_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='add_goods',
            field=models.BooleanField(default=False, verbose_name='Добавление товара'),
        ),
    ]
