# Generated by Django 5.1.4 on 2025-01-25 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0021_operation_add_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodslog',
            name='selling_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата продажи товара'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admins_panel.goods', verbose_name='Товар'),
        ),
    ]
