# Generated by Django 5.1.4 on 2025-01-31 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins_panel', '0022_goodslog_selling_date_operationlog_goods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='edit_goods',
        ),
    ]
